from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import re
import yaml


REQUIRED_FIELDS = {
    "id",
    "name",
    "category",
    "version",
    "status",
    "language",
    "tags",
    "goal",
    "use_cases",
    "prompt",
    "input_contract",
    "output_contract",
    "design_principles",
    "examples",
    "known_failures",
    "changelog",
}

VALID_STATUS = {"draft", "experimental", "stable", "deprecated"}


@dataclass
class ValidationIssue:
    path: Path
    message: str

    def __str__(self) -> str:
        return f"{self.path}: {self.message}"


def parse_front_matter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError("missing YAML front matter")
    parts = text.split("---", 2)
    if len(parts) != 3:
        raise ValueError("invalid YAML front matter")
    data = yaml.safe_load(parts[1]) or {}
    if not isinstance(data, dict):
        raise ValueError("front matter must be a mapping")
    return data


def validate_prompt_file(path: Path) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    try:
        data = parse_front_matter(path)
    except Exception as exc:
        return [ValidationIssue(path, str(exc))]

    missing = REQUIRED_FIELDS - set(data)
    for field in sorted(missing):
        issues.append(ValidationIssue(path, f"missing field: {field}"))

    if data.get("status") not in VALID_STATUS:
        issues.append(ValidationIssue(path, "status must be draft/experimental/stable/deprecated"))

    if not isinstance(data.get("tags"), list) or not data.get("tags"):
        issues.append(ValidationIssue(path, "tags must be a non-empty list"))

    if not isinstance(data.get("examples"), list) or not data.get("examples"):
        issues.append(ValidationIssue(path, "examples must be a non-empty list"))

    if not isinstance(data.get("changelog"), list) or not data.get("changelog"):
        issues.append(ValidationIssue(path, "changelog must be a non-empty list"))

    prompt = data.get("prompt", "")
    if not isinstance(prompt, str) or len(prompt.strip()) < 40:
        issues.append(ValidationIssue(path, "prompt is too short"))

    if isinstance(prompt, str):
        variables = re.findall(r"\{\{([A-Z][A-Z0-9_]*)\}\}", prompt)
        declared = data.get("variables", [])
        declared_names = {
            item.get("name")
            for item in declared
            if isinstance(item, dict)
        }
        undeclared = sorted(set(variables) - declared_names)
        for name in undeclared:
            issues.append(ValidationIssue(path, f"undeclared variable: {name}"))

    return issues


def discover_prompt_files(root: Path) -> list[Path]:
    return sorted((root / "prompts").rglob("*.md"))


def validate_all(root: Path) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    for path in discover_prompt_files(root):
        issues.extend(validate_prompt_file(path))
    return issues


def load_prompt(path: Path) -> dict[str, Any]:
    return parse_front_matter(path)


def search_prompts(root: Path, keyword: str) -> list[tuple[Path, dict[str, Any]]]:
    keyword = keyword.lower()
    results = []
    for path in discover_prompt_files(root):
        data = load_prompt(path)
        haystack = " ".join([
            str(data.get("name", "")),
            str(data.get("category", "")),
            str(data.get("goal", "")),
            str(data.get("tags", "")),
            str(data.get("prompt", "")),
        ]).lower()
        if keyword in haystack:
            results.append((path, data))
    return results


def generate_index(root: Path) -> Path:
    rows = []
    for path in discover_prompt_files(root):
        data = load_prompt(path)
        rows.append(
            f"| `{data.get('id', '')}` | [{data.get('name', '')}]({path.as_posix()}) "
            f"| {data.get('category', '')} | {', '.join(data.get('tags', []))} "
            f"| {data.get('status', '')} | {data.get('version', '')} |"
        )
    rows.sort()
    content = """# Prompt Index

Generated by `ichiban-prompt index`.

| ID | Name | Category | Tags | Status | Version |
|---|---|---|---|---|---|
""" + "\n".join(rows) + "\n"
    target = root / "INDEX.md"
    target.write_text(content, encoding="utf-8")
    return target
